//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePract.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoice_details()
        {
            this.tblinboice_products = new HashSet<tblinboice_products>();
            this.tblinvoice_payments = new HashSet<tblinvoice_payments>();
        }
    
        public int Invoice_id { get; set; }
        public Nullable<System.DateTime> Invoice_date { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public Nullable<double> Total_amount { get; set; }
    
        public virtual tblcustomer tblcustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinboice_products> tblinboice_products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoice_payments> tblinvoice_payments { get; set; }
    }
}
