//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePract.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventryDbEntities : DbContext
    {
        public InventryDbEntities()
            : base("name=InventryDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<invoice_details> invoice_details { get; set; }
        public virtual DbSet<tblcustomer> tblcustomers { get; set; }
        public virtual DbSet<tblinboice_products> tblinboice_products { get; set; }
        public virtual DbSet<tblinvoice_payments> tblinvoice_payments { get; set; }
        public virtual DbSet<tblproduct> tblproducts { get; set; }
    }
}
