//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePract.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinboice_products
    {
        public int Invoice_produce_id { get; set; }
        public Nullable<int> Invoice_id { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual invoice_details invoice_details { get; set; }
        public virtual tblproduct tblproduct { get; set; }
    }
}
