//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePract.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblproduct()
        {
            this.tblinboice_products = new HashSet<tblinboice_products>();
        }
    
        public int Product_id { get; set; }
        public string Product_name { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<int> Stock_quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinboice_products> tblinboice_products { get; set; }
    }
}
